this = _this;

removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

this forceAddUniform "MNP_CombatUniform_Scorpion_A";
for "_i" from 1 to 6 do {this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_morphine";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 2 do {this addItemToUniform "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToUniform "rhs_mag_an_m8hc";};
this addVest "MNP_Vest_Scorpion_1";
for "_i" from 1 to 2 do {this addItemToVest "rhs_200rnd_556x45_T_SAW";};
this addBackpack "B_Kitbag_rgr";
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_200rnd_556x45_T_SAW";};
this addHeadgear "H_HelmetSpecB_snakeskin";
this addWeapon "rhs_weap_m249_pip_L";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "rhsusf_ANPVS_15";
