this forceAddUniform "CUP_U_B_FR_DirAction2";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "CUP_V_B_RRV_Scout2";
for "_i" from 1 to 3 do {this addItemToVest "CUP_100Rnd_TE4_Red_Tracer_556x45_M249";};
this addHeadgear "CUP_H_USArmy_Helmet_ECH1_Green";
this addWeapon "CUP_lmg_m249_pip1";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "CUP_NVG_PVS14";
