this forceAddUniform "CUP_U_B_USMC_PilotOverall";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "CUP_V_B_PilotVest";
for "_i" from 1 to 5 do {this addItemToVest "CUP_30Rnd_9x19_MP5";};
for "_i" from 1 to 2 do {this addItemToVest "ACE_Chemlight_HiRed";};
this addItemToVest "ACE_HandFlare_Red";
this addItemToVest "ACE_HandFlare_Green";
for "_i" from 1 to 2 do {this addItemToVest "SmokeShellPurple";};
this addHeadgear "CUP_H_USMC_Helmet_Pilot";
this addWeapon "CUP_smg_MP5A5";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "CUP_NVG_PVS7";
