this forceAddUniform "CUP_U_B_FR_DirAction2";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
for "_i" from 1 to 2 do {this addItemToUniform "SmokeShell";};
for "_i" from 1 to 2 do {this addItemToUniform "CUP_HandGrenade_M67";};
this addVest "CUP_V_B_RRV_Scout2";
for "_i" from 1 to 10 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
this addBackpack "B_Carryall_oli";
for "_i" from 1 to 30 do {this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 10 do {this addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 8 do {this addItemToBackpack "ACE_salineIV_250";};
for "_i" from 1 to 7 do {this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_bodyBag";};
for "_i" from 1 to 20 do {this addItemToBackpack "ACE_splint";};
for "_i" from 1 to 4 do {this addItemToBackpack "ACE_salineIV";};
this addHeadgear "CUP_H_USArmy_Helmet_ECH1_Green";
this addWeapon "CUP_arifle_Mk16_STD_SFG_black";
this addPrimaryWeaponItem "CUP_acc_Flashlight";
this addPrimaryWeaponItem "CUP_optic_HoloBlack";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "CUP_NVG_PVS14";
