this forceAddUniform "rhs_uniform_cu_ucp_10th";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "rhsusf_spcs_ucp_rifleman";
for "_i" from 1 to 8 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
this addBackpack "B_Bergen_mcamo_F";
for "_i" from 1 to 10 do {this addItemToBackpack "rhs_mag_smaw_SR";};
for "_i" from 1 to 3 do {this addItemToBackpack "rhs_mag_smaw_HEAA";};
this addHeadgear "rhsusf_ach_helmet_headset_ess_ucp";
this addWeapon "rhs_weap_m4a1_carryhandle_mstock_grip2";
this addPrimaryWeaponItem "rhsusf_acc_SFMB556";
this addPrimaryWeaponItem "rhsusf_acc_anpeq15_light";
this addPrimaryWeaponItem "rhsusf_acc_compm4";
this addPrimaryWeaponItem "rhsusf_acc_grip2";
this addWeapon "rhs_weap_smaw_green";
this addSecondaryWeaponItem "rhs_weap_optic_smaw";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
