this forceAddUniform "rhs_uniform_cu_ucp_10th";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "rhsusf_iotv_ucp_SAW";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 4 do {this addItemToVest "hlc_100Rnd_762x51_T_M60E4";};
this addHeadgear "rhsusf_ach_helmet_headset_ess_ucp";
this addWeapon "rhs_weap_m240B";
this addPrimaryWeaponItem "rhsusf_acc_eotech_552";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
