{_x call f_fnc_setGroupID;false} count [
    // GROUP IDs: BLUFOR
    ["GrpBLUFOR_CO_CC","ColorOrange"],
    ["GrpBLUFOR_1PLT_CO","ColorYellow"],
    ["GrpBLUFOR_2PLT_CO","ColorYellow"],

    ["GrpBLUFOR_ASL","ColorRed"],
    ["GrpBLUFOR_A1","ColorRed"],
    ["GrpBLUFOR_A2","ColorRed"],
    ["GrpBLUFOR_A3","ColorRed"],

    ["GrpBLUFOR_BSL","ColorBlue"],
    ["GrpBLUFOR_B1","ColorBlue"],
    ["GrpBLUFOR_B2","ColorBlue"],
    ["GrpBLUFOR_B3","ColorBlue"],

    ["GrpBLUFOR_CSL","ColorGreen"],
    ["GrpBLUFOR_C1","ColorGreen"],
    ["GrpBLUFOR_C2","ColorGreen"],
    ["GrpBLUFOR_C3","ColorGreen"],

    ["GrpBLUFOR_DSL","ColorRed"],
    ["GrpBLUFOR_D1","ColorRed"],
    ["GrpBLUFOR_D2","ColorRed"],
    ["GrpBLUFOR_D3","ColorRed"],

    ["GrpBLUFOR_ESL","ColorBlue"],
    ["GrpBLUFOR_E1","ColorBlue"],
    ["GrpBLUFOR_E2","ColorBlue"],
    ["GrpBLUFOR_E3","ColorBlue"],

    ["GrpBLUFOR_FSL","ColorGreen"],
    ["GrpBLUFOR_F1","ColorGreen"],
    ["GrpBLUFOR_F2","ColorGreen"],
    ["GrpBLUFOR_F3","ColorGreen"],

    ["GrpBLUFOR_MMG1","ColorOrange"],
    ["GrpBLUFOR_MMG2","ColorOrange"],
    ["GrpBLUFOR_MMG3","ColorOrange"],
    ["GrpBLUFOR_MMG4","ColorOrange"],
    ["GrpBLUFOR_MMG5","ColorOrange"],
    ["GrpBLUFOR_MMG6","ColorOrange"],
    ["GrpBLUFOR_MMG7","ColorOrange"],
    ["GrpBLUFOR_MMG8","ColorOrange"],

    ["GrpBLUFOR_MAT1","ColorOrange"],
    ["GrpBLUFOR_MAT2","ColorOrange"],
    ["GrpBLUFOR_MAT3","ColorOrange"],
    ["GrpBLUFOR_MAT4","ColorOrange"],
    ["GrpBLUFOR_MAT5","ColorOrange"],
    ["GrpBLUFOR_MAT6","ColorOrange"],
    ["GrpBLUFOR_MAT7","ColorOrange"],
    ["GrpBLUFOR_MAT8","ColorOrange"],

    ["GrpBLUFOR_G1","ColorPink"],
    ["GrpBLUFOR_G2","ColorPink"],
    ["GrpBLUFOR_G3","ColorPink"],
    ["GrpBLUFOR_G4","ColorPink"],
    ["GrpBLUFOR_G5","ColorPink"],
    ["GrpBLUFOR_G6","ColorPink"],
    ["GrpBLUFOR_G7","ColorPink"],
    ["GrpBLUFOR_G8","ColorPink"],

    ["GrpBLUFOR_PH1","ColorRed"],
    ["GrpBLUFOR_PH2","ColorRed"],
    ["GrpBLUFOR_PH3","ColorRed"],
    ["GrpBLUFOR_PH4","ColorRed"],
    ["GrpBLUFOR_PH5","ColorRed"],
    ["GrpBLUFOR_PH6","ColorRed"],
    ["GrpBLUFOR_PH7","ColorRed"],
    ["GrpBLUFOR_PH8","ColorRed"],

    // GROUP IDs: OPFOR
    ["GrpOPFOR_CO_CC","ColorOrange"],
    ["GrpOPFOR_1PLT_CO","ColorYellow"],
    ["GrpOPFOR_2PLT_CO","ColorYellow"],

    ["GrpOPFOR_ASL","ColorRed"],
    ["GrpOPFOR_A1","ColorRed"],
    ["GrpOPFOR_A2","ColorRed"],
    ["GrpOPFOR_A3","ColorRed"],

    ["GrpOPFOR_BSL","ColorBlue"],
    ["GrpOPFOR_B1","ColorBlue"],
    ["GrpOPFOR_B2","ColorBlue"],
    ["GrpOPFOR_B3","ColorBlue"],

    ["GrpOPFOR_CSL","ColorGreen"],
    ["GrpOPFOR_C1","ColorGreen"],
    ["GrpOPFOR_C2","ColorGreen"],
    ["GrpOPFOR_C3","ColorGreen"],

    ["GrpOPFOR_DSL","ColorRed"],
    ["GrpOPFOR_D1","ColorRed"],
    ["GrpOPFOR_D2","ColorRed"],
    ["GrpOPFOR_D3","ColorRed"],

    ["GrpOPFOR_ESL","ColorBlue"],
    ["GrpOPFOR_E1","ColorBlue"],
    ["GrpOPFOR_E2","ColorBlue"],
    ["GrpOPFOR_E3","ColorBlue"],

    ["GrpOPFOR_FSL","ColorGreen"],
    ["GrpOPFOR_F1","ColorGreen"],
    ["GrpOPFOR_F2","ColorGreen"],
    ["GrpOPFOR_F3","ColorGreen"],

    ["GrpOPFOR_MMG1","ColorOrange"],
    ["GrpOPFOR_MMG2","ColorOrange"],
    ["GrpOPFOR_MMG3","ColorOrange"],
    ["GrpOPFOR_MMG4","ColorOrange"],
    ["GrpOPFOR_MMG5","ColorOrange"],
    ["GrpOPFOR_MMG6","ColorOrange"],
    ["GrpOPFOR_MMG7","ColorOrange"],
    ["GrpOPFOR_MMG8","ColorOrange"],

    ["GrpOPFOR_MAT1","ColorOrange"],
    ["GrpOPFOR_MAT2","ColorOrange"],
    ["GrpOPFOR_MAT3","ColorOrange"],
    ["GrpOPFOR_MAT4","ColorOrange"],
    ["GrpOPFOR_MAT5","ColorOrange"],
    ["GrpOPFOR_MAT6","ColorOrange"],
    ["GrpOPFOR_MAT7","ColorOrange"],
    ["GrpOPFOR_MAT8","ColorOrange"],

    ["GrpOPFOR_G1","ColorPink"],
    ["GrpOPFOR_G2","ColorPink"],
    ["GrpOPFOR_G3","ColorPink"],
    ["GrpOPFOR_G4","ColorPink"],
    ["GrpOPFOR_G5","ColorPink"],
    ["GrpOPFOR_G6","ColorPink"],
    ["GrpOPFOR_G7","ColorPink"],
    ["GrpOPFOR_G8","ColorPink"],

    ["GrpOPFOR_PH1","ColorRed"],
    ["GrpOPFOR_PH2","ColorRed"],
    ["GrpOPFOR_PH3","ColorRed"],
    ["GrpOPFOR_PH4","ColorRed"],
    ["GrpOPFOR_PH5","ColorRed"],
    ["GrpOPFOR_PH6","ColorRed"],
    ["GrpOPFOR_PH7","ColorRed"],
    ["GrpOPFOR_PH8","ColorRed"],

    // GROUP IDs: INDEPENDENT
    ["GrpINDFOR_CO_CC","ColorOrange"],
    ["GrpINDFOR_1PLT_CO","ColorYellow"],
    ["GrpINDFOR_2PLT_CO","ColorYellow"],

    ["GrpINDFOR_ASL","ColorRed"],
    ["GrpINDFOR_A1","ColorRed"],
    ["GrpINDFOR_A2","ColorRed"],
    ["GrpINDFOR_A3","ColorRed"],

    ["GrpINDFOR_BSL","ColorBlue"],
    ["GrpINDFOR_B1","ColorBlue"],
    ["GrpINDFOR_B2","ColorBlue"],
    ["GrpINDFOR_B3","ColorBlue"],

    ["GrpINDFOR_CSL","ColorGreen"],
    ["GrpINDFOR_C1","ColorGreen"],
    ["GrpINDFOR_C2","ColorGreen"],
    ["GrpINDFOR_C3","ColorGreen"],

    ["GrpINDFOR_DSL","ColorRed"],
    ["GrpINDFOR_D1","ColorRed"],
    ["GrpINDFOR_D2","ColorRed"],
    ["GrpINDFOR_D3","ColorRed"],

    ["GrpINDFOR_ESL","ColorBlue"],
    ["GrpINDFOR_E1","ColorBlue"],
    ["GrpINDFOR_E2","ColorBlue"],
    ["GrpINDFOR_E3","ColorBlue"],

    ["GrpINDFOR_FSL","ColorGreen"],
    ["GrpINDFOR_F1","ColorGreen"],
    ["GrpINDFOR_F2","ColorGreen"],
    ["GrpINDFOR_F3","ColorGreen"],

    ["GrpINDFOR_MMG1","ColorOrange"],
    ["GrpINDFOR_MMG2","ColorOrange"],
    ["GrpINDFOR_MMG3","ColorOrange"],
    ["GrpINDFOR_MMG4","ColorOrange"],
    ["GrpINDFOR_MMG5","ColorOrange"],
    ["GrpINDFOR_MMG6","ColorOrange"],
    ["GrpINDFOR_MMG7","ColorOrange"],
    ["GrpINDFOR_MMG8","ColorOrange"],

    ["GrpINDFOR_MAT1","ColorOrange"],
    ["GrpINDFOR_MAT2","ColorOrange"],
    ["GrpINDFOR_MAT3","ColorOrange"],
    ["GrpINDFOR_MAT4","ColorOrange"],
    ["GrpINDFOR_MAT5","ColorOrange"],
    ["GrpINDFOR_MAT6","ColorOrange"],
    ["GrpINDFOR_MAT7","ColorOrange"],
    ["GrpINDFOR_MAT8","ColorOrange"],

    ["GrpINDFOR_G1","ColorPink"],
    ["GrpINDFOR_G2","ColorPink"],
    ["GrpINDFOR_G3","ColorPink"],
    ["GrpINDFOR_G4","ColorPink"],
    ["GrpINDFOR_G5","ColorPink"],
    ["GrpINDFOR_G6","ColorPink"],
    ["GrpINDFOR_G7","ColorPink"],
    ["GrpINDFOR_G8","ColorPink"],

    ["GrpINDFOR_PH1","ColorRed"],
    ["GrpINDFOR_PH2","ColorRed"],
    ["GrpINDFOR_PH3","ColorRed"],
    ["GrpINDFOR_PH4","ColorRed"],
    ["GrpINDFOR_PH5","ColorRed"],
    ["GrpINDFOR_PH6","ColorRed"],
    ["GrpINDFOR_PH7","ColorRed"],
    ["GrpINDFOR_PH8","ColorRed"]
];