{_x call f_fnc_setGroupID;false} count [
    // GROUP IDs: BLUFOR
    ["GrpBLUFOR_CO_CC","CoyHQ","ColorBrown"],
    ["GrpBLUFOR_1PLT_CO","1CO","ColorBrown"],
    ["GrpBLUFOR_2PLT_CO","2CO","ColorBrown"],

    ["GrpBLUFOR_ASL","ASL","ColorRed"],
    ["GrpBLUFOR_A1","A1","colorOPFOR"],
    ["GrpBLUFOR_A2","A2","colorOPFOR"],
    ["GrpBLUFOR_A3","A3","colorOPFOR"],

    ["GrpBLUFOR_BSL","BSL","ColorBlue"],
    ["GrpBLUFOR_B1","B1","colorBLUFOR"],
    ["GrpBLUFOR_B2","B2","colorBLUFOR"],
    ["GrpBLUFOR_B3","B3","colorBLUFOR"],

    ["GrpBLUFOR_CSL","CSL","ColorGreen"],
    ["GrpBLUFOR_C1","C1","colorIndependent"],
    ["GrpBLUFOR_C2","C2","colorIndependent"],
    ["GrpBLUFOR_C3","C3","colorIndependent"],

    ["GrpBLUFOR_DSL","DSL","ColorRed"],
    ["GrpBLUFOR_D1","D1","colorOPFOR"],
    ["GrpBLUFOR_D2","D2","colorOPFOR"],
    ["GrpBLUFOR_D3","D3","colorOPFOR"],

    ["GrpBLUFOR_ESL","ESL","ColorBlue"],
    ["GrpBLUFOR_E1","E1","colorBLUFOR"],
    ["GrpBLUFOR_E2","E2","colorBLUFOR"],
    ["GrpBLUFOR_E3","E3","colorBLUFOR"],

    ["GrpBLUFOR_FSL","FSL","ColorGreen"],
    ["GrpBLUFOR_F1","F1","colorIndependent"],
    ["GrpBLUFOR_F2","F2","colorIndependent"],
    ["GrpBLUFOR_F3","F3","colorIndependent"],

    ["GrpBLUFOR_MMG1","MMG1","ColorOrange"],
    ["GrpBLUFOR_MMG2","MMG2","ColorOrange"],
    ["GrpBLUFOR_MMG3","MMG3","ColorOrange"],
    ["GrpBLUFOR_MMG4","MMG4","ColorOrange"],
    ["GrpBLUFOR_MMG5","MMG5","ColorOrange"],
    ["GrpBLUFOR_MMG6","MMG6","ColorOrange"],
    ["GrpBLUFOR_MMG7","MMG7","ColorOrange"],
    ["GrpBLUFOR_MMG8","MMG8","ColorOrange"],

    ["GrpBLUFOR_MAT1","MAT1","ColorOrange"],
    ["GrpBLUFOR_MAT2","MAT2","ColorOrange"],
    ["GrpBLUFOR_MAT3","MAT3","ColorOrange"],
    ["GrpBLUFOR_MAT4","MAT4","ColorOrange"],
    ["GrpBLUFOR_MAT5","MAT5","ColorOrange"],
    ["GrpBLUFOR_MAT6","MAT6","ColorOrange"],
    ["GrpBLUFOR_MAT7","MAT7","ColorOrange"],
    ["GrpBLUFOR_MAT8","MAT8","ColorOrange"],

    ["GrpBLUFOR_MTR1","MTR1","ColorOrange"],
    ["GrpBLUFOR_MTR2","MTR2","ColorOrange"],
    ["GrpBLUFOR_MTR3","MTR3","ColorOrange"],
    ["GrpBLUFOR_MTR4","MTR4","ColorOrange"],
    ["GrpBLUFOR_MTR5","MTR5","ColorOrange"],
    ["GrpBLUFOR_MTR6","MTR6","ColorOrange"],
    ["GrpBLUFOR_MTR7","MTR7","ColorOrange"],
    ["GrpBLUFOR_MTR8","MTR8","ColorOrange"],

    ["GrpBLUFOR_G1","G1","ColorYellowColorYellow"],
    ["GrpBLUFOR_G2","G2","ColorYellowColorYellow"],
    ["GrpBLUFOR_G3","G3","ColorYellowColorYellow"],
    ["GrpBLUFOR_G4","G4","ColorYellowColorYellow"],
    ["GrpBLUFOR_G5","G5","ColorYellowColorYellow"],
    ["GrpBLUFOR_G6","G6","ColorYellowColorYellow"],
    ["GrpBLUFOR_G7","G7","ColorYellowColorYellow"],
    ["GrpBLUFOR_G8","G8","ColorYellowColorYellow"],

    ["GrpBLUFOR_PH1","PH1","ColorUNKNOWN"],
    ["GrpBLUFOR_PH2","PH2","ColorUNKNOWN"],
    ["GrpBLUFOR_PH3","PH3","ColorUNKNOWN"],
    ["GrpBLUFOR_PH4","PH4","ColorUNKNOWN"],
    ["GrpBLUFOR_RVN1","RVN1","ColorBlack"],
    ["GrpBLUFOR_RVN2","RVN2","ColorBlack"],
    ["GrpBLUFOR_RVN3","RVN3","ColorBlack"],
    ["GrpBLUFOR_RVN4","RVN4","ColorBlack"],

    // GROUP IDs: OPFOR
    ["GrpOPFOR_CO_CC","CoyHQ","ColorBrown"],
    ["GrpOPFOR_1PLT_CO","1CO","ColorBrown"],
    ["GrpOPFOR_2PLT_CO","2CO","ColorBrown"],

    ["GrpOPFOR_ASL","ASL","ColorRed"],
    ["GrpOPFOR_A1","A1","colorOPFOR"],
    ["GrpOPFOR_A2","A2","colorOPFOR"],
    ["GrpOPFOR_A3","A3","colorOPFOR"],

    ["GrpOPFOR_BSL","BSL","ColorBlue"],
    ["GrpOPFOR_B1","B1","colorBLUFOR"],
    ["GrpOPFOR_B2","B2","colorBLUFOR"],
    ["GrpOPFOR_B3","B3","colorBLUFOR"],

    ["GrpOPFOR_CSL","CSL","ColorGreen"],
    ["GrpOPFOR_C1","C1","colorIndependent"],
    ["GrpOPFOR_C2","C2","colorIndependent"],
    ["GrpOPFOR_C3","C3","colorIndependent"],

    ["GrpOPFOR_DSL","DSL","ColorRed"],
    ["GrpOPFOR_D1","D1","colorOPFOR"],
    ["GrpOPFOR_D2","D2","colorOPFOR"],
    ["GrpOPFOR_D3","D3","colorOPFOR"],

    ["GrpOPFOR_ESL","ESL","ColorBlue"],
    ["GrpOPFOR_E1","E1","colorBLUFOR"],
    ["GrpOPFOR_E2","E2","colorBLUFOR"],
    ["GrpOPFOR_E3","E3","colorBLUFOR"],

    ["GrpOPFOR_FSL","FSL","ColorGreen"],
    ["GrpOPFOR_F1","F1","colorIndependent"],
    ["GrpOPFOR_F2","F2","colorIndependent"],
    ["GrpOPFOR_F3","F3","colorIndependent"],

    ["GrpOPFOR_MMG1","MMG1","ColorOrange"],
    ["GrpOPFOR_MMG2","MMG2","ColorOrange"],
    ["GrpOPFOR_MMG3","MMG3","ColorOrange"],
    ["GrpOPFOR_MMG4","MMG4","ColorOrange"],
    ["GrpOPFOR_MMG5","MMG5","ColorOrange"],
    ["GrpOPFOR_MMG6","MMG6","ColorOrange"],
    ["GrpOPFOR_MMG7","MMG7","ColorOrange"],
    ["GrpOPFOR_MMG8","MMG8","ColorOrange"],

    ["GrpOPFOR_MAT1","MAT1","ColorOrange"],
    ["GrpOPFOR_MAT2","MAT2","ColorOrange"],
    ["GrpOPFOR_MAT3","MAT3","ColorOrange"],
    ["GrpOPFOR_MAT4","MAT4","ColorOrange"],
    ["GrpOPFOR_MAT5","MAT5","ColorOrange"],
    ["GrpOPFOR_MAT6","MAT6","ColorOrange"],
    ["GrpOPFOR_MAT7","MAT7","ColorOrange"],
    ["GrpOPFOR_MAT8","MAT8","ColorOrange"],

    ["GrpOPFOR_MTR1","MTR1","ColorOrange"],
    ["GrpOPFOR_MTR2","MTR2","ColorOrange"],
    ["GrpOPFOR_MTR3","MTR3","ColorOrange"],
    ["GrpOPFOR_MTR4","MTR4","ColorOrange"],
    ["GrpOPFOR_MTR5","MTR5","ColorOrange"],
    ["GrpOPFOR_MTR6","MTR6","ColorOrange"],
    ["GrpOPFOR_MTR7","MTR7","ColorOrange"],
    ["GrpOPFOR_MTR8","MTR8","ColorOrange"],

    ["GrpOPFOR_G1","G1","ColorYellow"],
    ["GrpOPFOR_G2","G2","ColorYellow"],
    ["GrpOPFOR_G3","G3","ColorYellow"],
    ["GrpOPFOR_G4","G4","ColorYellow"],
    ["GrpOPFOR_G5","G5","ColorYellow"],
    ["GrpOPFOR_G6","G6","ColorYellow"],
    ["GrpOPFOR_G7","G7","ColorYellow"],
    ["GrpOPFOR_G8","G8","ColorYellow"],

    ["GrpOPFOR_PH1","PH1","ColorUNKNOWN"],
    ["GrpOPFOR_PH2","PH2","ColorUNKNOWN"],
    ["GrpOPFOR_PH3","PH3","ColorUNKNOWN"],
    ["GrpOPFOR_PH4","PH4","ColorUNKNOWN"],
    ["GrpOPFOR_RVN1","RVN1","ColorBlack"],
    ["GrpOPFOR_RVN2","RVN2","ColorBlack"],
    ["GrpOPFOR_RVN3","RVN3","ColorBlack"],
    ["GrpOPFOR_RVN4","RVN4","ColorBlack"],

    // GROUP IDs: INDEPENDENT
    ["GrpINDFOR_CO_CC","CO","ColorBrown"],
    ["GrpINDFOR_1PLT_CO","1PLT","ColorBrown"],
    ["GrpINDFOR_2PLT_CO","2PLT","ColorBrown"],

    ["GrpINDFOR_ASL","ASL","ColorRed"],
    ["GrpINDFOR_A1","A1","colorOPFOR"],
    ["GrpINDFOR_A2","A2","colorOPFOR"],
    ["GrpINDFOR_A3","A3","colorOPFOR"],

    ["GrpINDFOR_BSL","BSL","ColorBlue"],
    ["GrpINDFOR_B1","B1","colorBLUFOR"],
    ["GrpINDFOR_B2","B2","colorBLUFOR"],
    ["GrpINDFOR_B3","B3","colorBLUFOR"],

    ["GrpINDFOR_CSL","CSL","ColorGreen"],
    ["GrpINDFOR_C1","C1","colorIndependent"],
    ["GrpINDFOR_C2","C2","colorIndependent"],
    ["GrpINDFOR_C3","C3","colorIndependent"],

    ["GrpINDFOR_DSL","DSL","ColorRed"],
    ["GrpINDFOR_D1","D1","colorOPFOR"],
    ["GrpINDFOR_D2","D2","colorOPFOR"],
    ["GrpINDFOR_D3","D3","colorOPFOR"],

    ["GrpINDFOR_ESL","ESL","ColorBlue"],
    ["GrpINDFOR_E1","E1","colorBLUFOR"],
    ["GrpINDFOR_E2","E2","colorBLUFOR"],
    ["GrpINDFOR_E3","E3","colorBLUFOR"],

    ["GrpINDFOR_FSL","FSL","ColorGreen"],
    ["GrpINDFOR_F1","F1","colorIndependent"],
    ["GrpINDFOR_F2","F2","colorIndependent"],
    ["GrpINDFOR_F3","F3","colorIndependent"],

    ["GrpINDFOR_MMG1","MMG1","ColorOrange"],
    ["GrpINDFOR_MMG2","MMG2","ColorOrange"],
    ["GrpINDFOR_MMG3","MMG3","ColorOrange"],
    ["GrpINDFOR_MMG4","MMG4","ColorOrange"],
    ["GrpINDFOR_MMG5","MMG5","ColorOrange"],
    ["GrpINDFOR_MMG6","MMG6","ColorOrange"],
    ["GrpINDFOR_MMG7","MMG7","ColorOrange"],
    ["GrpINDFOR_MMG8","MMG8","ColorOrange"],

    ["GrpINDFOR_MAT1","MAT1","ColorOrange"],
    ["GrpINDFOR_MAT2","MAT2","ColorOrange"],
    ["GrpINDFOR_MAT3","MAT3","ColorOrange"],
    ["GrpINDFOR_MAT4","MAT4","ColorOrange"],
    ["GrpINDFOR_MAT5","MAT5","ColorOrange"],
    ["GrpINDFOR_MAT6","MAT6","ColorOrange"],
    ["GrpINDFOR_MAT7","MAT7","ColorOrange"],
    ["GrpINDFOR_MAT8","MAT8","ColorOrange"],

    ["GrpINDFOR_MTR1","MTR1","ColorOrange"],
    ["GrpINDFOR_MTR2","MTR2","ColorOrange"],
    ["GrpINDFOR_MTR3","MTR3","ColorOrange"],
    ["GrpINDFOR_MTR4","MTR4","ColorOrange"],
    ["GrpINDFOR_MTR5","MTR5","ColorOrange"],
    ["GrpINDFOR_MTR6","MTR6","ColorOrange"],
    ["GrpINDFOR_MTR7","MTR7","ColorOrange"],
    ["GrpINDFOR_MTR8","MTR8","ColorOrange"],

    ["GrpINDFOR_G1","G1","ColorYellow"],
    ["GrpINDFOR_G2","G2","ColorYellow"],
    ["GrpINDFOR_G3","G3","ColorYellow"],
    ["GrpINDFOR_G4","G4","ColorYellow"],
    ["GrpINDFOR_G5","G5","ColorYellow"],
    ["GrpINDFOR_G6","G6","ColorYellow"],
    ["GrpINDFOR_G7","G7","ColorYellow"],
    ["GrpINDFOR_G8","G8","ColorYellow"],

    ["GrpINDFOR_PH1","PH1","ColorUNKNOWN"],
    ["GrpINDFOR_PH2","PH2","ColorUNKNOWN"],
    ["GrpINDFOR_PH3","PH3","ColorUNKNOWN"],
    ["GrpINDFOR_PH4","PH4","ColorUNKNOWN"],
    ["GrpINDFOR_RVN1","RVN1","ColorBlack"],
    ["GrpINDFOR_RVN2","RVN2","ColorBlack"],
    ["GrpINDFOR_RVN3","RVN3","ColorBlack"],
    ["GrpINDFOR_RVN4","RVN4","ColorBlack"]
];
