_groups = [
    // GROUP IDs: BLUFOR > NATO
    ["GrpBLUFOR_CO_CC","CO","ColorOrange"],
    ["GrpBLUFOR_1PLT_CO","1PLT","ColorYellow"],
    ["GrpBLUFOR_2PLT_CO","2PLT","ColorYellow"],

    ["GrpBLUFOR_ASL","ASL","ColorRed"],
    ["GrpBLUFOR_A1","A1","ColorRed"],
    ["GrpBLUFOR_A2","A2","ColorRed"],
    ["GrpBLUFOR_A3","A3","ColorRed"],

    ["GrpBLUFOR_BSL","BSL","ColorBlue"],
    ["GrpBLUFOR_B1","B1","ColorBlue"],
    ["GrpBLUFOR_B2","B2","ColorBlue"],
    ["GrpBLUFOR_B3","B3","ColorBlue"],

    ["GrpBLUFOR_CSL","CSL","ColorGreen"],
    ["GrpBLUFOR_C1","C1","ColorGreen"],
    ["GrpBLUFOR_C2","C2","ColorGreen"],
    ["GrpBLUFOR_C3","C3","ColorGreen"],

    ["GrpBLUFOR_DSL","DSL","ColorRed"],
    ["GrpBLUFOR_D1","D1","ColorRed"],
    ["GrpBLUFOR_D2","D2","ColorRed"],
    ["GrpBLUFOR_D3","D3","ColorRed"],

    ["GrpBLUFOR_ESL","ESL","ColorBlue"],
    ["GrpBLUFOR_E1","E1","ColorBlue"],
    ["GrpBLUFOR_E2","E2","ColorBlue"],
    ["GrpBLUFOR_E3","E3","ColorBlue"],

    ["GrpBLUFOR_FSL","FSL","ColorGreen"],
    ["GrpBLUFOR_F1","F1","ColorGreen"],
    ["GrpBLUFOR_F2","F2","ColorGreen"],
    ["GrpBLUFOR_F3","F3","ColorGreen"],

    ["GrpBLUFOR_MMG1","MMG1","ColorOrange"],
    ["GrpBLUFOR_MMG2","MMG2","ColorOrange"],
    ["GrpBLUFOR_MMG3","MMG3","ColorOrange"],
    ["GrpBLUFOR_MMG4","MMG4","ColorOrange"],
    ["GrpBLUFOR_MMG5","MMG5","ColorOrange"],
    ["GrpBLUFOR_MMG6","MMG6","ColorOrange"],
    ["GrpBLUFOR_MMG7","MMG7","ColorOrange"],
    ["GrpBLUFOR_MMG8","MMG8","ColorOrange"],

    ["GrpBLUFOR_MAT1","MAT1","ColorOrange"],
    ["GrpBLUFOR_MAT2","MAT2","ColorOrange"],
    ["GrpBLUFOR_MAT3","MAT3","ColorOrange"],
    ["GrpBLUFOR_MAT4","MAT4","ColorOrange"],
    ["GrpBLUFOR_MAT5","MAT5","ColorOrange"],
    ["GrpBLUFOR_MAT6","MAT6","ColorOrange"],
    ["GrpBLUFOR_MAT7","MAT7","ColorOrange"],
    ["GrpBLUFOR_MAT8","MAT8","ColorOrange"],

    ["GrpBLUFOR_G1","G1","ColorPink"],
    ["GrpBLUFOR_G2","G2","ColorPink"],
    ["GrpBLUFOR_G3","G3","ColorPink"],
    ["GrpBLUFOR_G4","G4","ColorPink"],
    ["GrpBLUFOR_G5","G5","ColorPink"],
    ["GrpBLUFOR_G6","G6","ColorPink"],
    ["GrpBLUFOR_G7","G7","ColorPink"],
    ["GrpBLUFOR_G8","G8","ColorPink"],

    ["GrpBLUFOR_PH1","PH1","ColorCIV"],
    ["GrpBLUFOR_PH2","PH2","ColorCIV"],
    ["GrpBLUFOR_PH3","PH3","ColorCIV"],
    ["GrpBLUFOR_PH4","PH4","ColorCIV"],
    ["GrpBLUFOR_PH5","PH5","ColorCIV"],
    ["GrpBLUFOR_PH6","PH6","ColorCIV"],
    ["GrpBLUFOR_PH7","PH7","ColorCIV"],
    ["GrpBLUFOR_PH8","PH8","ColorCIV"],

    // GROUP IDs: OPFOR > CSAT
    ["GrpOPFOR_CO_CC","CO","ColorOrange"],
    ["GrpOPFOR_1PLT_CO","1PLT","ColorYellow"],
    ["GrpOPFOR_2PLT_CO","2PLT","ColorYellow"],

    ["GrpOPFOR_ASL","ASL","ColorRed"],
    ["GrpOPFOR_A1","A1","ColorRed"],
    ["GrpOPFOR_A2","A2","ColorRed"],
    ["GrpOPFOR_A3","A3","ColorRed"],

    ["GrpOPFOR_BSL","BSL","ColorBlue"],
    ["GrpOPFOR_B1","B1","ColorBlue"],
    ["GrpOPFOR_B2","B2","ColorBlue"],
    ["GrpOPFOR_B3","B3","ColorBlue"],

    ["GrpOPFOR_CSL","CSL","ColorGreen"],
    ["GrpOPFOR_C1","C1","ColorGreen"],
    ["GrpOPFOR_C2","C2","ColorGreen"],
    ["GrpOPFOR_C3","C3","ColorGreen"],

    ["GrpOPFOR_DSL","DSL","ColorRed"],
    ["GrpOPFOR_D1","D1","ColorRed"],
    ["GrpOPFOR_D2","D2","ColorRed"],
    ["GrpOPFOR_D3","D3","ColorRed"],

    ["GrpOPFOR_ESL","ESL","ColorBlue"],
    ["GrpOPFOR_E1","E1","ColorBlue"],
    ["GrpOPFOR_E2","E2","ColorBlue"],
    ["GrpOPFOR_E3","E3","ColorBlue"],

    ["GrpOPFOR_FSL","FSL","ColorGreen"],
    ["GrpOPFOR_F1","F1","ColorGreen"],
    ["GrpOPFOR_F2","F2","ColorGreen"],
    ["GrpOPFOR_F3","F3","ColorGreen"],

    ["GrpOPFOR_MMG1","MMG1","ColorOrange"],
    ["GrpOPFOR_MMG2","MMG2","ColorOrange"],
    ["GrpOPFOR_MMG3","MMG3","ColorOrange"],
    ["GrpOPFOR_MMG4","MMG4","ColorOrange"],
    ["GrpOPFOR_MMG5","MMG5","ColorOrange"],
    ["GrpOPFOR_MMG6","MMG6","ColorOrange"],
    ["GrpOPFOR_MMG7","MMG7","ColorOrange"],
    ["GrpOPFOR_MMG8","MMG8","ColorOrange"],

    ["GrpOPFOR_MAT1","MAT1","ColorOrange"],
    ["GrpOPFOR_MAT2","MAT2","ColorOrange"],
    ["GrpOPFOR_MAT3","MAT3","ColorOrange"],
    ["GrpOPFOR_MAT4","MAT4","ColorOrange"],
    ["GrpOPFOR_MAT5","MAT5","ColorOrange"],
    ["GrpOPFOR_MAT6","MAT6","ColorOrange"],
    ["GrpOPFOR_MAT7","MAT7","ColorOrange"],
    ["GrpOPFOR_MAT8","MAT8","ColorOrange"],

    ["GrpOPFOR_G1","G1","ColorPink"],
    ["GrpOPFOR_G2","G2","ColorPink"],
    ["GrpOPFOR_G3","G3","ColorPink"],
    ["GrpOPFOR_G4","G4","ColorPink"],
    ["GrpOPFOR_G5","G5","ColorPink"],
    ["GrpOPFOR_G6","G6","ColorPink"],
    ["GrpOPFOR_G7","G7","ColorPink"],
    ["GrpOPFOR_G8","G8","ColorPink"],

    ["GrpOPFOR_PH1","PH1","ColorCIV"],
    ["GrpOPFOR_PH2","PH2","ColorCIV"],
    ["GrpOPFOR_PH3","PH3","ColorCIV"],
    ["GrpOPFOR_PH4","PH4","ColorCIV"],
    ["GrpOPFOR_PH5","PH5","ColorCIV"],
    ["GrpOPFOR_PH6","PH6","ColorCIV"],
    ["GrpOPFOR_PH7","PH7","ColorCIV"],
    ["GrpOPFOR_PH8","PH8","ColorCIV"],

    // GROUP IDs: INDEPENDENT > AAF
    ["GrpINDFOR_CO_CC","CO","ColorOrange"],
    ["GrpINDFOR_1PLT_CO","1PLT","ColorYellow"],
    ["GrpINDFOR_2PLT_CO","2PLT","ColorYellow"],

    ["GrpINDFOR_ASL","ASL","ColorRed"],
    ["GrpINDFOR_A1","A1","ColorRed"],
    ["GrpINDFOR_A2","A2","ColorRed"],
    ["GrpINDFOR_A3","A3","ColorRed"],

    ["GrpINDFOR_BSL","BSL","ColorBlue"],
    ["GrpINDFOR_B1","B1","ColorBlue"],
    ["GrpINDFOR_B2","B2","ColorBlue"],
    ["GrpINDFOR_B3","B3","ColorBlue"],

    ["GrpINDFOR_CSL","CSL","ColorGreen"],
    ["GrpINDFOR_C1","C1","ColorGreen"],
    ["GrpINDFOR_C2","C2","ColorGreen"],
    ["GrpINDFOR_C3","C3","ColorGreen"],

    ["GrpINDFOR_DSL","DSL","ColorRed"],
    ["GrpINDFOR_D1","D1","ColorRed"],
    ["GrpINDFOR_D2","D2","ColorRed"],
    ["GrpINDFOR_D3","D3","ColorRed"],

    ["GrpINDFOR_ESL","ESL","ColorBlue"],
    ["GrpINDFOR_E1","E1","ColorBlue"],
    ["GrpINDFOR_E2","E2","ColorBlue"],
    ["GrpINDFOR_E3","E3","ColorBlue"],

    ["GrpINDFOR_FSL","FSL","ColorGreen"],
    ["GrpINDFOR_F1","F1","ColorGreen"],
    ["GrpINDFOR_F2","F2","ColorGreen"],
    ["GrpINDFOR_F3","F3","ColorGreen"],

    ["GrpINDFOR_MMG1","MMG1","ColorOrange"],
    ["GrpINDFOR_MMG2","MMG2","ColorOrange"],
    ["GrpINDFOR_MMG3","MMG3","ColorOrange"],
    ["GrpINDFOR_MMG4","MMG4","ColorOrange"],
    ["GrpINDFOR_MMG5","MMG5","ColorOrange"],
    ["GrpINDFOR_MMG6","MMG6","ColorOrange"],
    ["GrpINDFOR_MMG7","MMG7","ColorOrange"],
    ["GrpINDFOR_MMG8","MMG8","ColorOrange"],

    ["GrpINDFOR_MAT1","MAT1","ColorOrange"],
    ["GrpINDFOR_MAT2","MAT2","ColorOrange"],
    ["GrpINDFOR_MAT3","MAT3","ColorOrange"],
    ["GrpINDFOR_MAT4","MAT4","ColorOrange"],
    ["GrpINDFOR_MAT5","MAT5","ColorOrange"],
    ["GrpINDFOR_MAT6","MAT6","ColorOrange"],
    ["GrpINDFOR_MAT7","MAT7","ColorOrange"],
    ["GrpINDFOR_MAT8","MAT8","ColorOrange"],

    ["GrpINDFOR_G1","G1","ColorPink"],
    ["GrpINDFOR_G2","G2","ColorPink"],
    ["GrpINDFOR_G3","G3","ColorPink"],
    ["GrpINDFOR_G4","G4","ColorPink"],
    ["GrpINDFOR_G5","G5","ColorPink"],
    ["GrpINDFOR_G6","G6","ColorPink"],
    ["GrpINDFOR_G7","G7","ColorPink"],
    ["GrpINDFOR_G8","G8","ColorPink"],

    ["GrpINDFOR_PH1","PH1","ColorCIV"],
    ["GrpINDFOR_PH2","PH2","ColorCIV"],
    ["GrpINDFOR_PH3","PH3","ColorCIV"],
    ["GrpINDFOR_PH4","PH4","ColorCIV"],
    ["GrpINDFOR_PH5","PH5","ColorCIV"],
    ["GrpINDFOR_PH6","PH6","ColorCIV"],
    ["GrpINDFOR_PH7","PH7","ColorCIV"],
    ["GrpINDFOR_PH8","PH8","ColorCIV"]
];

{_x call f_fnc_setGroupID;false} count _groups;