this forceAddUniform "rhs_uniform_msv_emr";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
this addVest "rhs_6b23_6sh116_od";
for "_i" from 1 to 6 do {this addItemToVest "hlc_30Rnd_762x39_b_ak";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rdg2_black";};
this addItemToVest "rhs_mag_9x19_17";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rgd5";};
this addBackpack "rhs_assault_umbts";
for "_i" from 1 to 4 do {this addItemToBackpack "hlc_30Rnd_762x39_b_ak";};
for "_i" from 1 to 7 do {this addItemToBackpack "hlc_45Rnd_545x39_t_rpk";};
this addHeadgear "rhs_6b7_1m_emr_ess_bala";
this addWeapon "rhs_weap_ak103";
this addWeapon "rhs_weap_pya";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "rhs_1PN138";
