this forceAddUniform "rhs_uniform_msv_emr";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EntrenchingTool";
this addVest "rhs_6b23_6sh116_od";
for "_i" from 1 to 3 do {this addItemToVest "hlc_30Rnd_762x39_b_ak";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rdg2_black";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_rgd5";};
this addBackpack "B_Carryall_oli";
for "_i" from 1 to 6 do {this addItemToBackpack "hlc_30Rnd_762x39_b_ak";};
for "_i" from 1 to 3 do {this addItemToBackpack "rhs_rpg7_PG7VL_mag";};
this addItemToBackpack "rhs_rpg7_OG7V_mag";
this addItemToBackpack "rhs_rpg7_TBG7V_mag";
this addHeadgear "rhs_6b7_1m_emr_ess_bala";
this addWeapon "rhs_weap_ak103";
this addWeapon "rhs_weap_rpg7";
this addSecondaryWeaponItem "rhs_acc_pgo7v";
this addWeapon "rhs_weap_pya";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "rhs_1PN138";
