this forceAddUniform "rhs_uniform_gorka_r_g";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addVest "rhs_6b23_crew";
for "_i" from 1 to 4 do {this addItemToVest "rhs_30Rnd_545x39_AK";};
this addItemToVest "rhs_mag_m18_green";
this addItemToVest "rhs_mag_m18_red";
this addItemToVest "rhs_mag_9x19_17";
this addHeadgear "rhs_zsh7a_mike_green";
this addWeapon "rhs_weap_ak74m_folded";
this addWeapon "rhs_weap_pya";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "rhs_1PN138";
