this forceAddUniform "rhs_uniform_msv_emr";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_Flashlight_KSF1";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_CableTie";
this addVest "rhs_6b23_crew";
for "_i" from 1 to 6 do {this addItemToVest "hlc_30Rnd_762x39_b_ak";};
this addItemToVest "rhs_mag_m18_green";
this addItemToVest "rhs_mag_m18_red";
this addItemToVest "rhs_mag_9x19_17";
this addHeadgear "rhs_tsh4";
this addWeapon "rhs_weap_ak103";
this addWeapon "rhs_weap_pya";
this addWeapon "Binocular";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "rhs_1PN138";
