this forceAddUniform "CUP_U_B_BAF_MTP_S5_UnRolled";
for "_i" from 1 to 5 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_BAF_Osprey_Mk4_MTP_MachineGunner";
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_L109A1_HE";};
this addItemToVest "SmokeShell";
for "_i" from 1 to 2 do {this addItemToVest "CUP_200Rnd_TE4_Red_Tracer_556x45_M249";};
this addBackpack "CUP_B_Bergen_BAF";
for "_i" from 1 to 2 do {this addItemToBackpack "CUP_200Rnd_TE4_Red_Tracer_556x45_M249";};
this addHeadgear "CUP_H_BAF_Helmet_3_MTP";
this addWeapon "CUP_lmg_L110A1";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemRadioAcreFlagged";
this linkItem "ItemGPS";