this forceAddUniform "MNP_CombatUniform_Germany";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addVest "V_TacVest_blk";
this addItemToVest "rhsusf_mag_17Rnd_9x19_FMJ";
for "_i" from 1 to 6 do {this addItemToVest "hlc_30Rnd_9x19_B_MP5";};
this addItemToVest "rhs_mag_m18_green";
this addItemToVest "rhs_mag_m18_red";
this addHeadgear "MNP_Helmet_Dslyecxi";
this addWeapon "hlc_smg_mp5a3";
this addWeapon "rhsusf_weap_glock17g4";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
this linkItem "rhsusf_ANPVS_15";
