this forceAddUniform "MNP_CombatUniform_Germany";
for "_i" from 1 to 2 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_tourniquet";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_IR_Strobe_Item";
this addItemToUniform "ACE_Flashlight_XL50";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_EntrenchingTool";
this addVest "MNP_Vest_Germany_2";
for "_i" from 1 to 10 do {this addItemToVest "hlc_30rnd_556x45_EPR_G36";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_an_m8hc";};
this addItemToVest "rhsusf_mag_17Rnd_9x19_FMJ";
this addBackpack "B_Carryall_oli";
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_smaw_HEAA";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_smaw_SR";};
this addHeadgear "MNP_Helmet_Germany";
this addWeapon "hlc_rifle_G36V";
this addPrimaryWeaponItem "rhsusf_acc_anpeq15_bk";
this addWeapon "rhsusf_weap_glock17g4";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "rhsusf_ANPVS_15";
