this forceAddUniform "CUP_U_B_BAF_MTP_S6_UnRolled";
for "_i" from 1 to 3 do {this addItemToUniform "ACE_fieldDressing";};
this addItemToUniform "ACE_CableTie";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_morphine";
this addItemToUniform "ACE_tourniquet";
this addVest "CUP_V_BAF_Osprey_Mk4_MTP_Rifleman";
for "_i" from 1 to 6 do {this addItemToVest "CUP_30Rnd_556x45_Stanag";};
for "_i" from 1 to 4 do {this addItemToVest "30Rnd_556x45_Stanag_Tracer_Red";};
for "_i" from 1 to 2 do {this addItemToVest "CUP_HandGrenade_L109A1_HE";};
this addItemToVest "SmokeShell";
this addBackpack "CUP_B_Bergen_BAF";
this addItemToBackpack "CUP_MAAWS_HEDP_M";
this addItemToBackpack "CUP_MAAWS_HEAT_M";
this addHeadgear "CUP_H_BAF_Helmet_2_MTP";
this addWeapon "CUP_arifle_L85A2";
this addWeapon "CUP_launch_MAAWS";
this addSecondaryWeaponItem "CUP_optic_MAAWS_Scope";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "ItemGPS";
